// Code generated by hiro; DO NOT EDIT.

// Copyright 2018 Portworx Inc. All rights reserved.
// Use of this source code is governed by the Apache 2.0
// license that can be found in the LICENSE file at the
// root of this project.

package sample

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
	"gitlab.com/ModelRocket/sparks/cloud/provider"
)

// SampleDeleteHandlerFunc turns a function with the right signature into a sample delete handler
type SampleDeleteHandlerFunc func(SampleDeleteParams, provider.AuthToken) middleware.Responder

// Handle executing the request and returning a response
func (fn SampleDeleteHandlerFunc) Handle(params SampleDeleteParams, principal provider.AuthToken) middleware.Responder {
	return fn(params, principal)
}

// SampleDeleteHandler interface for that can handle valid sample delete params
type SampleDeleteHandler interface {
	Handle(SampleDeleteParams, provider.AuthToken) middleware.Responder
}

// NewSampleDelete creates a new http.Handler for the sample delete operation
func NewSampleDelete(ctx *middleware.Context, handler SampleDeleteHandler) *SampleDelete {
	return &SampleDelete{Context: ctx, Handler: handler}
}

/*SampleDelete swagger:route DELETE /samples/{sample_id} sample sampleDelete

Get a list of telemetry samples

Returns the request collected object

*/
type SampleDelete struct {
	Context *middleware.Context
	Handler SampleDeleteHandler
}

func (o *SampleDelete) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewSampleDeleteParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal provider.AuthToken
	if uprinc != nil {
		principal = uprinc.(provider.AuthToken) // this is really a provider.AuthToken, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
