// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2018 Portworx Inc. All rights reserved.
// Use of this source code is governed by the Apache 2.0
// license that can be found in the LICENSE file at the
// root of this project.

package sample

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	types "github.com/libopenstorage/autopilot/api/autopilot/types"
)

// SampleDeleteNoContentCode is the HTTP code returned for type SampleDeleteNoContent
const SampleDeleteNoContentCode int = 204

/*SampleDeleteNoContent No content

swagger:response sampleDeleteNoContent
*/
type SampleDeleteNoContent struct {
}

// NewSampleDeleteNoContent creates SampleDeleteNoContent with default headers values
func NewSampleDeleteNoContent() *SampleDeleteNoContent {

	return &SampleDeleteNoContent{}
}

// WriteResponse to the client
func (o *SampleDeleteNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

// SampleDeleteNotFoundCode is the HTTP code returned for type SampleDeleteNotFound
const SampleDeleteNotFoundCode int = 404

/*SampleDeleteNotFound NotFound

swagger:response sampleDeleteNotFound
*/
type SampleDeleteNotFound struct {

	/*
	  In: Body
	*/
	Payload *types.Error `json:"body,omitempty"`
}

// NewSampleDeleteNotFound creates SampleDeleteNotFound with default headers values
func NewSampleDeleteNotFound() *SampleDeleteNotFound {

	return &SampleDeleteNotFound{}
}

// WithPayload adds the payload to the sample delete not found response
func (o *SampleDeleteNotFound) WithPayload(payload *types.Error) *SampleDeleteNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the sample delete not found response
func (o *SampleDeleteNotFound) SetPayload(payload *types.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SampleDeleteNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// SampleDeleteInternalServerErrorCode is the HTTP code returned for type SampleDeleteInternalServerError
const SampleDeleteInternalServerErrorCode int = 500

/*SampleDeleteInternalServerError ServerError

swagger:response sampleDeleteInternalServerError
*/
type SampleDeleteInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *types.Error `json:"body,omitempty"`
}

// NewSampleDeleteInternalServerError creates SampleDeleteInternalServerError with default headers values
func NewSampleDeleteInternalServerError() *SampleDeleteInternalServerError {

	return &SampleDeleteInternalServerError{}
}

// WithPayload adds the payload to the sample delete internal server error response
func (o *SampleDeleteInternalServerError) WithPayload(payload *types.Error) *SampleDeleteInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the sample delete internal server error response
func (o *SampleDeleteInternalServerError) SetPayload(payload *types.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SampleDeleteInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
