sudo: required
dist: trusty
language: go
go:
  - 1.10.4
before_install:
  - sudo apt-get update -yq
script:
  - |
    make && make pretest && make container
    if [ "${TRAVIS_PULL_REQUEST}" == "false" ]; then
      docker login -u "${DOCKER_USER}" -p "${DOCKER_PASSWORD}";
      make deploy
    fi
notifications:
  email:
    on_success: always
    on_failure: always
