// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2018 Portworx Inc. All rights reserved.
// Use of this source code is governed by the Apache 2.0
// license that can be found in the LICENSE file at the
// root of this project.

package source

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/validate"

	strfmt "github.com/go-openapi/strfmt"

	types "github.com/libopenstorage/autopilot/api/autopilot/types"
)

// NewSourceUpdateParams creates a new SourceUpdateParams object
// no default values defined in spec.
func NewSourceUpdateParams() SourceUpdateParams {

	return SourceUpdateParams{}
}

// SourceUpdateParams contains all the bound params for the source update operation
// typically these are obtained from a http.Request
//
// swagger:parameters sourceUpdate
type SourceUpdateParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*The source to create
	  Required: true
	  In: body
	*/
	Source *types.Source
	/*The id of the source
	  Required: true
	  In: path
	*/
	SourceID strfmt.UUID
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewSourceUpdateParams() beforehand.
func (o *SourceUpdateParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body types.Source
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("source", "body"))
			} else {
				res = append(res, errors.NewParseError("source", "body", "", err))
			}
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Source = &body
			}
		}
	} else {
		res = append(res, errors.Required("source", "body"))
	}
	rSourceID, rhkSourceID, _ := route.Params.GetOK("source_id")
	if err := o.bindSourceID(rSourceID, rhkSourceID, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindSourceID binds and validates parameter SourceID from path.
func (o *SourceUpdateParams) bindSourceID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	// Format: uuid
	value, err := formats.Parse("uuid", raw)
	if err != nil {
		return errors.InvalidType("source_id", "path", "strfmt.UUID", raw)
	}
	o.SourceID = *(value.(*strfmt.UUID))

	if err := o.validateSourceID(formats); err != nil {
		return err
	}

	return nil
}

// validateSourceID carries on validations for parameter SourceID
func (o *SourceUpdateParams) validateSourceID(formats strfmt.Registry) error {

	if err := validate.FormatOf("source_id", "path", "uuid", o.SourceID.String(), formats); err != nil {
		return err
	}
	return nil
}
