// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2018 Portworx Inc. All rights reserved.
// Use of this source code is governed by the Apache 2.0
// license that can be found in the LICENSE file at the
// root of this project.

package source

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	types "github.com/libopenstorage/autopilot/api/autopilot/types"
)

// SourceDeleteNoContentCode is the HTTP code returned for type SourceDeleteNoContent
const SourceDeleteNoContentCode int = 204

/*SourceDeleteNoContent No Content

swagger:response sourceDeleteNoContent
*/
type SourceDeleteNoContent struct {
}

// NewSourceDeleteNoContent creates SourceDeleteNoContent with default headers values
func NewSourceDeleteNoContent() *SourceDeleteNoContent {

	return &SourceDeleteNoContent{}
}

// WriteResponse to the client
func (o *SourceDeleteNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

// SourceDeleteNotFoundCode is the HTTP code returned for type SourceDeleteNotFound
const SourceDeleteNotFoundCode int = 404

/*SourceDeleteNotFound NotFound

swagger:response sourceDeleteNotFound
*/
type SourceDeleteNotFound struct {

	/*
	  In: Body
	*/
	Payload *types.Error `json:"body,omitempty"`
}

// NewSourceDeleteNotFound creates SourceDeleteNotFound with default headers values
func NewSourceDeleteNotFound() *SourceDeleteNotFound {

	return &SourceDeleteNotFound{}
}

// WithPayload adds the payload to the source delete not found response
func (o *SourceDeleteNotFound) WithPayload(payload *types.Error) *SourceDeleteNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the source delete not found response
func (o *SourceDeleteNotFound) SetPayload(payload *types.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SourceDeleteNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// SourceDeleteInternalServerErrorCode is the HTTP code returned for type SourceDeleteInternalServerError
const SourceDeleteInternalServerErrorCode int = 500

/*SourceDeleteInternalServerError ServerError

swagger:response sourceDeleteInternalServerError
*/
type SourceDeleteInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *types.Error `json:"body,omitempty"`
}

// NewSourceDeleteInternalServerError creates SourceDeleteInternalServerError with default headers values
func NewSourceDeleteInternalServerError() *SourceDeleteInternalServerError {

	return &SourceDeleteInternalServerError{}
}

// WithPayload adds the payload to the source delete internal server error response
func (o *SourceDeleteInternalServerError) WithPayload(payload *types.Error) *SourceDeleteInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the source delete internal server error response
func (o *SourceDeleteInternalServerError) SetPayload(payload *types.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SourceDeleteInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
