// Code generated by hiro; DO NOT EDIT.

// Copyright 2018 Portworx Inc. All rights reserved.
// Use of this source code is governed by the Apache 2.0
// license that can be found in the LICENSE file at the
// root of this project.

package source

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// SourcePollHandlerFunc turns a function with the right signature into a source poll handler
type SourcePollHandlerFunc func(SourcePollParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn SourcePollHandlerFunc) Handle(params SourcePollParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// SourcePollHandler interface for that can handle valid source poll params
type SourcePollHandler interface {
	Handle(SourcePollParams, interface{}) middleware.Responder
}

// NewSourcePoll creates a new http.Handler for the source poll operation
func NewSourcePoll(ctx *middleware.Context, handler SourcePollHandler) *SourcePoll {
	return &SourcePoll{Context: ctx, Handler: handler}
}

/*SourcePoll swagger:route GET /sources/{source_id}/poll source sourcePoll

Poll a source

Poll a source and collect a sample manually

*/
type SourcePoll struct {
	Context *middleware.Context
	Handler SourcePollHandler
}

func (o *SourcePoll) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewSourcePollParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
