// Code generated by hiro; DO NOT EDIT.

// Copyright 2018 Portworx Inc. All rights reserved.
// Use of this source code is governed by the Apache 2.0
// license that can be found in the LICENSE file at the
// root of this project.

package source

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// SourceCreateHandlerFunc turns a function with the right signature into a source create handler
type SourceCreateHandlerFunc func(SourceCreateParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn SourceCreateHandlerFunc) Handle(params SourceCreateParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// SourceCreateHandler interface for that can handle valid source create params
type SourceCreateHandler interface {
	Handle(SourceCreateParams, interface{}) middleware.Responder
}

// NewSourceCreate creates a new http.Handler for the source create operation
func NewSourceCreate(ctx *middleware.Context, handler SourceCreateHandler) *SourceCreate {
	return &SourceCreate{Context: ctx, Handler: handler}
}

/*SourceCreate swagger:route POST /sources source sourceCreate

Create a new telemetry source

Create a new telemetry source from the provided definition

*/
type SourceCreate struct {
	Context *middleware.Context
	Handler SourceCreateHandler
}

func (o *SourceCreate) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewSourceCreateParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
