// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2018 Portworx Inc. All rights reserved.
// Use of this source code is governed by the Apache 2.0
// license that can be found in the LICENSE file.

package rest

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "swagger": "2.0",
  "info": {
    "description": "libopenstorage autopilot API",
    "title": "autopilot",
    "license": {
      "name": "Apache 2.0",
      "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
    },
    "version": "1.0.0"
  },
  "paths": {
    "/sources": {
      "get": {
        "description": "Returns an array of telemetry sources defined in the system",
        "summary": "Get a list of telemetry sources",
        "operationId": "sourceList",
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Source"
              }
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Source": {
      "description": "A definition for a telemetry source",
      "properties": {
        "id": {
          "type": "string",
          "format": "uuid"
        }
      },
      "example": {
        "id": "046b6c7f-0b8a-43b9-b35d-6489e6daee91"
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "swagger": "2.0",
  "info": {
    "description": "libopenstorage autopilot API",
    "title": "autopilot",
    "license": {
      "name": "Apache 2.0",
      "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
    },
    "version": "1.0.0"
  },
  "paths": {
    "/sources": {
      "get": {
        "description": "Returns an array of telemetry sources defined in the system",
        "summary": "Get a list of telemetry sources",
        "operationId": "sourceList",
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Source"
              }
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Source": {
      "description": "A definition for a telemetry source",
      "properties": {
        "id": {
          "type": "string",
          "format": "uuid"
        }
      },
      "example": {
        "id": "046b6c7f-0b8a-43b9-b35d-6489e6daee91"
      }
    }
  }
}`))
}
