/*
Copyright 2019 Openstorage.org

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	autopilotv1alpha1 "github.com/libopenstorage/autopilot/pkg/apis/autopilot/v1alpha1"
	versioned "github.com/libopenstorage/autopilot/pkg/client/clientset/versioned"
	internalinterfaces "github.com/libopenstorage/autopilot/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/libopenstorage/autopilot/pkg/client/listers/autopilot/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// StoragePolicyInformer provides access to a shared informer and lister for
// StoragePolicies.
type StoragePolicyInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.StoragePolicyLister
}

type storagePolicyInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewStoragePolicyInformer constructs a new informer for StoragePolicy type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewStoragePolicyInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredStoragePolicyInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredStoragePolicyInformer constructs a new informer for StoragePolicy type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredStoragePolicyInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AutopilotV1alpha1().StoragePolicies().List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AutopilotV1alpha1().StoragePolicies().Watch(options)
			},
		},
		&autopilotv1alpha1.StoragePolicy{},
		resyncPeriod,
		indexers,
	)
}

func (f *storagePolicyInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredStoragePolicyInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *storagePolicyInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&autopilotv1alpha1.StoragePolicy{}, f.defaultInformer)
}

func (f *storagePolicyInformer) Lister() v1alpha1.StoragePolicyLister {
	return v1alpha1.NewStoragePolicyLister(f.Informer().GetIndexer())
}
