// Code generated by go-swagger (hiro); DO NOT EDIT.

// Copyright 2018 Portworx Inc. All rights reserved.
// Use of this source code is governed by the Apache 2.0
// license that can be found in the LICENSE file at the
// root of this project.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"bytes"
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// AutoPilot The AutoPilot provider configuration
// swagger:model AutoPilot
type AutoPilot struct {
	nameField string ``

	// Addition provider params
	Params map[string]interface{} `json:"params,omitempty"`
}

// Name gets the name of this subtype
func (m *AutoPilot) Name() string {
	return m.nameField
}

// SetName sets the name of this subtype
func (m *AutoPilot) SetName(val string) {
	m.nameField = val
}

// Type gets the type of this subtype
func (m *AutoPilot) Type() ProviderType {
	return "AutoPilot"
}

// SetType sets the type of this subtype
func (m *AutoPilot) SetType(val ProviderType) {

}

// Params gets the params of this subtype

// UnmarshalJSON unmarshals this object with a polymorphic type from a JSON structure
func (m *AutoPilot) UnmarshalJSON(raw []byte) error {
	var data struct {

		// Addition provider params
		Params map[string]interface{} `json:"params,omitempty"`
	}
	buf := bytes.NewBuffer(raw)
	dec := json.NewDecoder(buf)
	dec.UseNumber()

	if err := dec.Decode(&data); err != nil {
		return err
	}

	var base struct {
		/* Just the base type fields. Used for unmashalling polymorphic types.*/

		Name string `json:"name,omitempty"`

		Type ProviderType `json:"type,omitempty"`
	}
	buf = bytes.NewBuffer(raw)
	dec = json.NewDecoder(buf)
	dec.UseNumber()

	if err := dec.Decode(&base); err != nil {
		return err
	}

	var result AutoPilot

	result.nameField = base.Name

	if base.Type != result.Type() {
		/* Not the type we're looking for. */
		return errors.New(422, "invalid type value: %q", base.Type)
	}

	result.Params = data.Params

	*m = result

	return nil
}

// MarshalJSON marshals this object with a polymorphic type to a JSON structure
func (m AutoPilot) MarshalJSON() ([]byte, error) {
	var b1, b2, b3 []byte
	var err error
	b1, err = json.Marshal(struct {

		// Addition provider params
		Params map[string]interface{} `json:"params,omitempty"`
	}{

		Params: m.Params,
	},
	)
	if err != nil {
		return nil, err
	}
	b2, err = json.Marshal(struct {
		Name string `json:"name,omitempty"`

		Type ProviderType `json:"type,omitempty"`
	}{

		Name: m.Name(),

		Type: m.Type(),
	},
	)
	if err != nil {
		return nil, err
	}

	return swag.ConcatJSON(b1, b2, b3), nil
}

// Validate validates this auto pilot
func (m *AutoPilot) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *AutoPilot) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AutoPilot) UnmarshalBinary(b []byte) error {
	var res AutoPilot
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
