// Code generated by go-swagger (hiro); DO NOT EDIT.

// Copyright 2018 Portworx Inc. All rights reserved.
// Use of this source code is governed by the Apache 2.0
// license that can be found in the LICENSE file at the
// root of this project.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Emitter An emitter emits recommendations to a target
//
// swagger:model Emitter
type Emitter struct {

	// The emitter name
	Name string `json:"name,omitempty"`

	// json data object
	Params map[string]interface{} `json:"params,omitempty"`

	// The emitter type
	// Enum: [mqtt]
	Type string `json:"type,omitempty"`
}

// Validate validates this emitter
func (m *Emitter) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var emitterTypeTypePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["mqtt"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		emitterTypeTypePropEnum = append(emitterTypeTypePropEnum, v)
	}
}

const (

	// EmitterTypeMqtt captures enum value "mqtt"
	EmitterTypeMqtt string = "mqtt"
)

// prop value enum
func (m *Emitter) validateTypeEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, emitterTypeTypePropEnum); err != nil {
		return err
	}
	return nil
}

func (m *Emitter) validateType(formats strfmt.Registry) error {

	if swag.IsZero(m.Type) { // not required
		return nil
	}

	// value enum
	if err := m.validateTypeEnum("type", "body", m.Type); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Emitter) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Emitter) UnmarshalBinary(b []byte) error {
	var res Emitter
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
