// Code generated by go-swagger (hiro); DO NOT EDIT.

// Copyright 2018 Portworx Inc. All rights reserved.
// Use of this source code is governed by the Apache 2.0
// license that can be found in the LICENSE file at the
// root of this project.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"bytes"
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// PrometheusCollector Prometheus collector type
// swagger:model PrometheusCollector
type PrometheusCollector struct {
	emittersField []string

	nameField string

	scheduleIntervalField string

	urlField string

	// The query to run against the prometheus host
	Query string `json:"query,omitempty"`

	// The sample size for the interval
	SampleInterval *string `json:"sample_interval,omitempty"`
}

// Emitters gets the emitters of this subtype
func (m *PrometheusCollector) Emitters() []string {
	return m.emittersField
}

// SetEmitters sets the emitters of this subtype
func (m *PrometheusCollector) SetEmitters(val []string) {
	m.emittersField = val
}

// Name gets the name of this subtype
func (m *PrometheusCollector) Name() string {
	return m.nameField
}

// SetName sets the name of this subtype
func (m *PrometheusCollector) SetName(val string) {
	m.nameField = val
}

// ScheduleInterval gets the schedule interval of this subtype
func (m *PrometheusCollector) ScheduleInterval() string {
	return m.scheduleIntervalField
}

// SetScheduleInterval sets the schedule interval of this subtype
func (m *PrometheusCollector) SetScheduleInterval(val string) {
	m.scheduleIntervalField = val
}

// Type gets the type of this subtype
func (m *PrometheusCollector) Type() CollectorType {
	return "PrometheusCollector"
}

// SetType sets the type of this subtype
func (m *PrometheusCollector) SetType(val CollectorType) {

}

// URL gets the url of this subtype
func (m *PrometheusCollector) URL() string {
	return m.urlField
}

// SetURL sets the url of this subtype
func (m *PrometheusCollector) SetURL(val string) {
	m.urlField = val
}

// Query gets the query of this subtype

// SampleInterval gets the sample interval of this subtype

// UnmarshalJSON unmarshals this object with a polymorphic type from a JSON structure
func (m *PrometheusCollector) UnmarshalJSON(raw []byte) error {
	var data struct {

		// The query to run against the prometheus host
		Query string `json:"query,omitempty"`

		// The sample size for the interval
		SampleInterval *string `json:"sample_interval,omitempty"`
	}
	buf := bytes.NewBuffer(raw)
	dec := json.NewDecoder(buf)
	dec.UseNumber()

	if err := dec.Decode(&data); err != nil {
		return err
	}

	var base struct {
		/* Just the base type fields. Used for unmashalling polymorphic types.*/

		Emitters []string `json:"emitters"`

		Name string `json:"name,omitempty"`

		ScheduleInterval string `json:"schedule_interval,omitempty"`

		Type CollectorType `json:"type,omitempty"`

		URL string `json:"url,omitempty"`
	}
	buf = bytes.NewBuffer(raw)
	dec = json.NewDecoder(buf)
	dec.UseNumber()

	if err := dec.Decode(&base); err != nil {
		return err
	}

	var result PrometheusCollector

	result.emittersField = base.Emitters

	result.nameField = base.Name

	result.scheduleIntervalField = base.ScheduleInterval

	if base.Type != result.Type() {
		/* Not the type we're looking for. */
		return errors.New(422, "invalid type value: %q", base.Type)
	}

	result.urlField = base.URL

	result.Query = data.Query

	result.SampleInterval = data.SampleInterval

	*m = result

	return nil
}

// MarshalJSON marshals this object with a polymorphic type to a JSON structure
func (m PrometheusCollector) MarshalJSON() ([]byte, error) {
	var b1, b2, b3 []byte
	var err error
	b1, err = json.Marshal(struct {

		// The query to run against the prometheus host
		Query string `json:"query,omitempty"`

		// The sample size for the interval
		SampleInterval *string `json:"sample_interval,omitempty"`
	}{

		Query: m.Query,

		SampleInterval: m.SampleInterval,
	},
	)
	if err != nil {
		return nil, err
	}
	b2, err = json.Marshal(struct {
		Emitters []string `json:"emitters,omitempty"`

		Name string `json:"name,omitempty"`

		ScheduleInterval string `json:"schedule_interval,omitempty"`

		Type CollectorType `json:"type,omitempty"`

		URL string `json:"url,omitempty"`
	}{

		Emitters: m.Emitters(),

		Name: m.Name(),

		ScheduleInterval: m.ScheduleInterval(),

		Type: m.Type(),

		URL: m.URL(),
	},
	)
	if err != nil {
		return nil, err
	}

	return swag.ConcatJSON(b1, b2, b3), nil
}

// Validate validates this prometheus collector
func (m *PrometheusCollector) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *PrometheusCollector) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PrometheusCollector) UnmarshalBinary(b []byte) error {
	var res PrometheusCollector
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
