// Code generated by go-swagger (hiro); DO NOT EDIT.

// Copyright 2018 Portworx Inc. All rights reserved.
// Use of this source code is governed by the Apache 2.0
// license that can be found in the LICENSE file at the
// root of this project.
//

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// Proposal A proposal is a formatted propsal object
//
// swagger:model Proposal
type Proposal struct {

	// The proposed action to take to resolve the issue
	Action string `json:"action,omitempty"`

	// The cluster id
	Cluster string `json:"cluster,omitempty"`

	// Issue from the rule that describes the reason for this proposal
	Issue string `json:"issue,omitempty"`

	// The node id
	Node string `json:"node,omitempty"`

	// The rule that triggered the proposal
	Rule string `json:"rule,omitempty"`

	// The volume id
	Volume string `json:"volume,omitempty"`
}

// Validate validates this proposal
func (m *Proposal) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Proposal) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Proposal) UnmarshalBinary(b []byte) error {
	var res Proposal
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
