// Code generated by hiro; DO NOT EDIT.

// Copyright 2018 Portworx Inc. All rights reserved.
// Use of this source code is governed by the Apache 2.0
// license that can be found in the LICENSE file at the
// root of this project.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
	"gitlab.com/ModelRocket/sparks/cloud/provider"
)

// CollectorCreateHandlerFunc turns a function with the right signature into a collector create handler
type CollectorCreateHandlerFunc func(CollectorCreateParams, provider.AuthToken) middleware.Responder

// Handle executing the request and returning a response
func (fn CollectorCreateHandlerFunc) Handle(params CollectorCreateParams, principal provider.AuthToken) middleware.Responder {
	return fn(params, principal)
}

// CollectorCreateHandler interface for that can handle valid collector create params
type CollectorCreateHandler interface {
	Handle(CollectorCreateParams, provider.AuthToken) middleware.Responder
}

// NewCollectorCreate creates a new http.Handler for the collector create operation
func NewCollectorCreate(ctx *middleware.Context, handler CollectorCreateHandler) *CollectorCreate {
	return &CollectorCreate{Context: ctx, Handler: handler}
}

/*CollectorCreate swagger:route POST /collectors collectorCreate

Create a new telemetry collector

Create a new telemetry collector from the provided definition

*/
type CollectorCreate struct {
	Context *middleware.Context
	Handler CollectorCreateHandler
}

func (o *CollectorCreate) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewCollectorCreateParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal provider.AuthToken
	if uprinc != nil {
		principal = uprinc.(provider.AuthToken) // this is really a provider.AuthToken, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
