// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2018 Portworx Inc. All rights reserved.
// Use of this source code is governed by the Apache 2.0
// license that can be found in the LICENSE file at the
// root of this project.
//

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	types "github.com/libopenstorage/autopilot/api/autopilot/types"
)

// ProviderQueryOKCode is the HTTP code returned for type ProviderQueryOK
const ProviderQueryOKCode int = 200

/*ProviderQueryOK OK

swagger:response providerQueryOK
*/
type ProviderQueryOK struct {

	/*
	  In: Body
	*/
	Payload []*types.Collector `json:"body,omitempty"`
}

// NewProviderQueryOK creates ProviderQueryOK with default headers values
func NewProviderQueryOK() *ProviderQueryOK {

	return &ProviderQueryOK{}
}

// WithPayload adds the payload to the provider query o k response
func (o *ProviderQueryOK) WithPayload(payload []*types.Collector) *ProviderQueryOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the provider query o k response
func (o *ProviderQueryOK) SetPayload(payload []*types.Collector) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ProviderQueryOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make([]*types.Collector, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// ProviderQueryInternalServerErrorCode is the HTTP code returned for type ProviderQueryInternalServerError
const ProviderQueryInternalServerErrorCode int = 500

/*ProviderQueryInternalServerError ServerError

swagger:response providerQueryInternalServerError
*/
type ProviderQueryInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *types.Error `json:"body,omitempty"`
}

// NewProviderQueryInternalServerError creates ProviderQueryInternalServerError with default headers values
func NewProviderQueryInternalServerError() *ProviderQueryInternalServerError {

	return &ProviderQueryInternalServerError{}
}

// WithPayload adds the payload to the provider query internal server error response
func (o *ProviderQueryInternalServerError) WithPayload(payload *types.Error) *ProviderQueryInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the provider query internal server error response
func (o *ProviderQueryInternalServerError) SetPayload(payload *types.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ProviderQueryInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
