// Code generated by hiro; DO NOT EDIT.

// Copyright 2018 Portworx Inc. All rights reserved.
// Use of this source code is governed by the Apache 2.0
// license that can be found in the LICENSE file at the
// root of this project.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
	"gitlab.com/ModelRocket/sparks/cloud/provider"
)

// RecommendationsGetHandlerFunc turns a function with the right signature into a recommendations get handler
type RecommendationsGetHandlerFunc func(RecommendationsGetParams, provider.AuthToken) middleware.Responder

// Handle executing the request and returning a response
func (fn RecommendationsGetHandlerFunc) Handle(params RecommendationsGetParams, principal provider.AuthToken) middleware.Responder {
	return fn(params, principal)
}

// RecommendationsGetHandler interface for that can handle valid recommendations get params
type RecommendationsGetHandler interface {
	Handle(RecommendationsGetParams, provider.AuthToken) middleware.Responder
}

// NewRecommendationsGet creates a new http.Handler for the recommendations get operation
func NewRecommendationsGet(ctx *middleware.Context, handler RecommendationsGetHandler) *RecommendationsGet {
	return &RecommendationsGet{Context: ctx, Handler: handler}
}

/*RecommendationsGet swagger:route POST /recommend recommendationsGet

Post a telemetry sample and get recommendations

Create a new telemetry sample from the provided definition and get recommendations

*/
type RecommendationsGet struct {
	Context *middleware.Context
	Handler RecommendationsGetHandler
}

func (o *RecommendationsGet) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewRecommendationsGetParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal provider.AuthToken
	if uprinc != nil {
		principal = uprinc.(provider.AuthToken) // this is really a provider.AuthToken, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
