// Code generated by hiro; DO NOT EDIT.

// Copyright 2018 Portworx Inc. All rights reserved.
// Use of this source code is governed by the Apache 2.0
// license that can be found in the LICENSE file at the
// root of this project.

package task

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
	"gitlab.com/ModelRocket/sparks/cloud/provider"
)

// TaskListHandlerFunc turns a function with the right signature into a task list handler
type TaskListHandlerFunc func(TaskListParams, provider.AuthToken) middleware.Responder

// Handle executing the request and returning a response
func (fn TaskListHandlerFunc) Handle(params TaskListParams, principal provider.AuthToken) middleware.Responder {
	return fn(params, principal)
}

// TaskListHandler interface for that can handle valid task list params
type TaskListHandler interface {
	Handle(TaskListParams, provider.AuthToken) middleware.Responder
}

// NewTaskList creates a new http.Handler for the task list operation
func NewTaskList(ctx *middleware.Context, handler TaskListHandler) *TaskList {
	return &TaskList{Context: ctx, Handler: handler}
}

/*TaskList swagger:route GET /tasks task taskList

Get a list of tasks

Returns an array of tasks

*/
type TaskList struct {
	Context *middleware.Context
	Handler TaskListHandler
}

func (o *TaskList) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewTaskListParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal provider.AuthToken
	if uprinc != nil {
		principal = uprinc.(provider.AuthToken) // this is really a provider.AuthToken, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
