// Code generated by hiro; DO NOT EDIT.

// Copyright 2018 Portworx Inc. All rights reserved.
// Use of this source code is governed by the Apache 2.0
// license that can be found in the LICENSE file at the
// root of this project.
//

package rest

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/dre1080/recover"
	"github.com/go-openapi/errors"
	"github.com/go-openapi/loads"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/sirupsen/logrus"

	interpose "github.com/carbocation/interpose/middleware"
	sparks "gitlab.com/ModelRocket/sparks/types"

	"github.com/libopenstorage/autopilot/api/autopilot"
	"github.com/libopenstorage/autopilot/api/autopilot/rest/operations"
)

type contextKey string

const AuthKey contextKey = "Auth"

// OperationsAPI
type OperationsAPI interface {
	// CollectorList is Returns an array of telemetry collectors defined in the system
	CollectorList(ctx *autopilot.Context, params operations.CollectorListParams) middleware.Responder
	// CollectorPoll is Poll a collector for the given period directly
	CollectorPoll(ctx *autopilot.Context, params operations.CollectorPollParams) middleware.Responder
	// EmitterList is Returns an array of telemetry emitters defined in the system
	EmitterList(ctx *autopilot.Context, params operations.EmitterListParams) middleware.Responder
	// ProviderList is Returns an array of telemetry providers defined in the system
	ProviderList(ctx *autopilot.Context, params operations.ProviderListParams) middleware.Responder
	// ProviderQuery is Query a provider directly
	ProviderQuery(ctx *autopilot.Context, params operations.ProviderQueryParams) middleware.Responder
	// RecommendationsGet is Create a new telemetry sample from the provided definition and get recommendations
	RecommendationsGet(ctx *autopilot.Context, params operations.RecommendationsGetParams) middleware.Responder
	// RuleList is Returns an array of telemetry rules defined in the system
	RuleList(ctx *autopilot.Context, params operations.RuleListParams) middleware.Responder
}

type AutopilotAPI interface {
	OperationsAPI
	// Initialize is called during handler creation to perform and changes during startup
	Initialize() error

	// InitializeContext is call before the api methods are executed
	InitializeContext(principal interface{}, r *http.Request) (*autopilot.Context, error)
}

// Config is configuration for Handler
type Config struct {
	AutopilotAPI
	Logger *logrus.Logger
	// InnerMiddleware is for the handler executors. These do not apply to the swagger.json document.
	// The middleware executes after routing but before authentication, binding and validation
	InnerMiddleware func(http.Handler) http.Handler

	// AuthBasicAuth for basic authentication
	AuthBasicAuth func(ctx context.Context, user string, pass string) (context.Context, interface{}, error)
}

// Handler returns an http.Handler given the handler configuration
// It mounts all the business logic implementers in the right routing.
func Handler(c Config) (http.Handler, error) {
	spec, err := loads.Analyzed(swaggerCopy(SwaggerJSON), "")
	if err != nil {
		return nil, fmt.Errorf("analyze swagger: %v", err)
	}
	api := operations.NewAutopilotAPI(spec)
	api.ServeError = errors.ServeError
	api.Logger = c.Logger.Printf

	api.JSONConsumer = runtime.JSONConsumer()
	api.JSONProducer = runtime.JSONProducer()
	api.BasicAuthAuth = func(ctx context.Context, user string, pass string) (context.Context, interface{}, error) {
		if c.AuthBasicAuth == nil {
			return ctx, nil, sparks.ErrNotAuthorized
		}
		return c.AuthBasicAuth(ctx, user, pass)
	}

	api.CollectorListHandler = operations.CollectorListHandlerFunc(func(params operations.CollectorListParams, principal interface{}) middleware.Responder {
		ctx, err := c.InitializeContext(principal, params.HTTPRequest)
		if err != nil {
			return sparks.NewError(err)
		}
		return c.AutopilotAPI.CollectorList(ctx, params)
	})
	api.CollectorPollHandler = operations.CollectorPollHandlerFunc(func(params operations.CollectorPollParams, principal interface{}) middleware.Responder {
		ctx, err := c.InitializeContext(principal, params.HTTPRequest)
		if err != nil {
			return sparks.NewError(err)
		}
		return c.AutopilotAPI.CollectorPoll(ctx, params)
	})
	api.EmitterListHandler = operations.EmitterListHandlerFunc(func(params operations.EmitterListParams, principal interface{}) middleware.Responder {
		ctx, err := c.InitializeContext(principal, params.HTTPRequest)
		if err != nil {
			return sparks.NewError(err)
		}
		return c.AutopilotAPI.EmitterList(ctx, params)
	})
	api.ProviderListHandler = operations.ProviderListHandlerFunc(func(params operations.ProviderListParams, principal interface{}) middleware.Responder {
		ctx, err := c.InitializeContext(principal, params.HTTPRequest)
		if err != nil {
			return sparks.NewError(err)
		}
		return c.AutopilotAPI.ProviderList(ctx, params)
	})
	api.ProviderQueryHandler = operations.ProviderQueryHandlerFunc(func(params operations.ProviderQueryParams, principal interface{}) middleware.Responder {
		ctx, err := c.InitializeContext(principal, params.HTTPRequest)
		if err != nil {
			return sparks.NewError(err)
		}
		return c.AutopilotAPI.ProviderQuery(ctx, params)
	})
	api.RecommendationsGetHandler = operations.RecommendationsGetHandlerFunc(func(params operations.RecommendationsGetParams, principal interface{}) middleware.Responder {
		ctx, err := c.InitializeContext(principal, params.HTTPRequest)
		if err != nil {
			return sparks.NewError(err)
		}
		return c.AutopilotAPI.RecommendationsGet(ctx, params)
	})
	api.RuleListHandler = operations.RuleListHandlerFunc(func(params operations.RuleListParams, principal interface{}) middleware.Responder {
		ctx, err := c.InitializeContext(principal, params.HTTPRequest)
		if err != nil {
			return sparks.NewError(err)
		}
		return c.AutopilotAPI.RuleList(ctx, params)
	})
	api.ServerShutdown = func() {}

	logMiddleware := func(handler http.Handler) http.Handler {
		handlePanic := recover.New(&recover.Options{
			Log: c.Logger.Error,
		})

		logViaLogrus := interpose.NegroniLogrus()

		if c.InnerMiddleware != nil {
			handler = c.InnerMiddleware(handler)
		}

		return handlePanic(logViaLogrus(handler))
	}

	if err := c.AutopilotAPI.Initialize(); err != nil {
		return nil, err
	}

	return api.Serve(logMiddleware), nil
}

// swaggerCopy copies the swagger json to prevent data races in runtime
func swaggerCopy(orig json.RawMessage) json.RawMessage {
	c := make(json.RawMessage, len(orig))
	copy(c, orig)
	return c
}
