// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2018 Portworx Inc. All rights reserved.
// Use of this source code is governed by the Apache 2.0
// license that can be found in the LICENSE file at the
// root of this project.

package collector

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	types "github.com/libopenstorage/autopilot/api/autopilot/types"
)

// CollectorPollOKCode is the HTTP code returned for type CollectorPollOK
const CollectorPollOKCode int = 200

/*CollectorPollOK OK

swagger:response collectorPollOK
*/
type CollectorPollOK struct {

	/*
	  In: Body
	*/
	Payload []types.Collector `json:"body,omitempty"`
}

// NewCollectorPollOK creates CollectorPollOK with default headers values
func NewCollectorPollOK() *CollectorPollOK {

	return &CollectorPollOK{}
}

// WithPayload adds the payload to the collector poll o k response
func (o *CollectorPollOK) WithPayload(payload []types.Collector) *CollectorPollOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the collector poll o k response
func (o *CollectorPollOK) SetPayload(payload []types.Collector) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CollectorPollOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make([]types.Collector, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// CollectorPollInternalServerErrorCode is the HTTP code returned for type CollectorPollInternalServerError
const CollectorPollInternalServerErrorCode int = 500

/*CollectorPollInternalServerError ServerError

swagger:response collectorPollInternalServerError
*/
type CollectorPollInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *types.Error `json:"body,omitempty"`
}

// NewCollectorPollInternalServerError creates CollectorPollInternalServerError with default headers values
func NewCollectorPollInternalServerError() *CollectorPollInternalServerError {

	return &CollectorPollInternalServerError{}
}

// WithPayload adds the payload to the collector poll internal server error response
func (o *CollectorPollInternalServerError) WithPayload(payload *types.Error) *CollectorPollInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the collector poll internal server error response
func (o *CollectorPollInternalServerError) SetPayload(payload *types.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CollectorPollInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
