// Code generated by hiro; DO NOT EDIT.

// Copyright 2018 Portworx Inc. All rights reserved.
// Use of this source code is governed by the Apache 2.0
// license that can be found in the LICENSE file at the
// root of this project.

package rule

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// RuleListHandlerFunc turns a function with the right signature into a rule list handler
type RuleListHandlerFunc func(RuleListParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn RuleListHandlerFunc) Handle(params RuleListParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// RuleListHandler interface for that can handle valid rule list params
type RuleListHandler interface {
	Handle(RuleListParams, interface{}) middleware.Responder
}

// NewRuleList creates a new http.Handler for the rule list operation
func NewRuleList(ctx *middleware.Context, handler RuleListHandler) *RuleList {
	return &RuleList{Context: ctx, Handler: handler}
}

/*RuleList swagger:route GET /rules rule ruleList

Get a list of telemetry rules

Returns an array of telemetry rules defined in the system

*/
type RuleList struct {
	Context *middleware.Context
	Handler RuleListHandler
}

func (o *RuleList) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewRuleListParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
