// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2018 Portworx Inc. All rights reserved.
// Use of this source code is governed by the Apache 2.0
// license that can be found in the LICENSE file at the
// root of this project.

package provider

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	types "github.com/libopenstorage/autopilot/api/autopilot/types"
)

// ProviderDeleteNoContentCode is the HTTP code returned for type ProviderDeleteNoContent
const ProviderDeleteNoContentCode int = 204

/*ProviderDeleteNoContent No Content

swagger:response providerDeleteNoContent
*/
type ProviderDeleteNoContent struct {
}

// NewProviderDeleteNoContent creates ProviderDeleteNoContent with default headers values
func NewProviderDeleteNoContent() *ProviderDeleteNoContent {

	return &ProviderDeleteNoContent{}
}

// WriteResponse to the client
func (o *ProviderDeleteNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

// ProviderDeleteNotFoundCode is the HTTP code returned for type ProviderDeleteNotFound
const ProviderDeleteNotFoundCode int = 404

/*ProviderDeleteNotFound NotFound

swagger:response providerDeleteNotFound
*/
type ProviderDeleteNotFound struct {

	/*
	  In: Body
	*/
	Payload *types.Error `json:"body,omitempty"`
}

// NewProviderDeleteNotFound creates ProviderDeleteNotFound with default headers values
func NewProviderDeleteNotFound() *ProviderDeleteNotFound {

	return &ProviderDeleteNotFound{}
}

// WithPayload adds the payload to the provider delete not found response
func (o *ProviderDeleteNotFound) WithPayload(payload *types.Error) *ProviderDeleteNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the provider delete not found response
func (o *ProviderDeleteNotFound) SetPayload(payload *types.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ProviderDeleteNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ProviderDeleteInternalServerErrorCode is the HTTP code returned for type ProviderDeleteInternalServerError
const ProviderDeleteInternalServerErrorCode int = 500

/*ProviderDeleteInternalServerError ServerError

swagger:response providerDeleteInternalServerError
*/
type ProviderDeleteInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *types.Error `json:"body,omitempty"`
}

// NewProviderDeleteInternalServerError creates ProviderDeleteInternalServerError with default headers values
func NewProviderDeleteInternalServerError() *ProviderDeleteInternalServerError {

	return &ProviderDeleteInternalServerError{}
}

// WithPayload adds the payload to the provider delete internal server error response
func (o *ProviderDeleteInternalServerError) WithPayload(payload *types.Error) *ProviderDeleteInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the provider delete internal server error response
func (o *ProviderDeleteInternalServerError) SetPayload(payload *types.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ProviderDeleteInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
