// Code generated by hiro; DO NOT EDIT.

// Copyright 2018 Portworx Inc. All rights reserved.
// Use of this source code is governed by the Apache 2.0
// license that can be found in the LICENSE file at the
// root of this project.

package provider

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
	"gitlab.com/ModelRocket/sparks/cloud/provider"
)

// ProviderUpdateHandlerFunc turns a function with the right signature into a provider update handler
type ProviderUpdateHandlerFunc func(ProviderUpdateParams, provider.AuthToken) middleware.Responder

// Handle executing the request and returning a response
func (fn ProviderUpdateHandlerFunc) Handle(params ProviderUpdateParams, principal provider.AuthToken) middleware.Responder {
	return fn(params, principal)
}

// ProviderUpdateHandler interface for that can handle valid provider update params
type ProviderUpdateHandler interface {
	Handle(ProviderUpdateParams, provider.AuthToken) middleware.Responder
}

// NewProviderUpdate creates a new http.Handler for the provider update operation
func NewProviderUpdate(ctx *middleware.Context, handler ProviderUpdateHandler) *ProviderUpdate {
	return &ProviderUpdate{Context: ctx, Handler: handler}
}

/*ProviderUpdate swagger:route PUT /providers/{provider_id} provider providerUpdate

Update a provider object

Update the properties of the specified provider

*/
type ProviderUpdate struct {
	Context *middleware.Context
	Handler ProviderUpdateHandler
}

func (o *ProviderUpdate) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewProviderUpdateParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal provider.AuthToken
	if uprinc != nil {
		principal = uprinc.(provider.AuthToken) // this is really a provider.AuthToken, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
