// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2018 Portworx Inc. All rights reserved.
// Use of this source code is governed by the Apache 2.0
// license that can be found in the LICENSE file at the
// root of this project.

package emitter

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/validate"

	strfmt "github.com/go-openapi/strfmt"

	types "github.com/libopenstorage/autopilot/api/autopilot/types"
)

// NewEmitterUpdateParams creates a new EmitterUpdateParams object
// no default values defined in spec.
func NewEmitterUpdateParams() EmitterUpdateParams {

	return EmitterUpdateParams{}
}

// EmitterUpdateParams contains all the bound params for the emitter update operation
// typically these are obtained from a http.Request
//
// swagger:parameters emitterUpdate
type EmitterUpdateParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*The emitter to create
	  Required: true
	  In: body
	*/
	Emitter *types.Emitter
	/*The id of the emitter
	  Required: true
	  In: path
	*/
	EmitterID strfmt.UUID
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewEmitterUpdateParams() beforehand.
func (o *EmitterUpdateParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body types.Emitter
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("emitter", "body"))
			} else {
				res = append(res, errors.NewParseError("emitter", "body", "", err))
			}
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Emitter = &body
			}
		}
	} else {
		res = append(res, errors.Required("emitter", "body"))
	}
	rEmitterID, rhkEmitterID, _ := route.Params.GetOK("emitter_id")
	if err := o.bindEmitterID(rEmitterID, rhkEmitterID, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindEmitterID binds and validates parameter EmitterID from path.
func (o *EmitterUpdateParams) bindEmitterID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	// Format: uuid
	value, err := formats.Parse("uuid", raw)
	if err != nil {
		return errors.InvalidType("emitter_id", "path", "strfmt.UUID", raw)
	}
	o.EmitterID = *(value.(*strfmt.UUID))

	if err := o.validateEmitterID(formats); err != nil {
		return err
	}

	return nil
}

// validateEmitterID carries on validations for parameter EmitterID
func (o *EmitterUpdateParams) validateEmitterID(formats strfmt.Registry) error {

	if err := validate.FormatOf("emitter_id", "path", "uuid", o.EmitterID.String(), formats); err != nil {
		return err
	}
	return nil
}
