// Code generated by hiro; DO NOT EDIT.

// Copyright 2018 Portworx Inc. All rights reserved.
// Use of this source code is governed by the Apache 2.0
// license that can be found in the LICENSE file at the
// root of this project.

package emitter

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// EmitterDeleteHandlerFunc turns a function with the right signature into a emitter delete handler
type EmitterDeleteHandlerFunc func(EmitterDeleteParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn EmitterDeleteHandlerFunc) Handle(params EmitterDeleteParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// EmitterDeleteHandler interface for that can handle valid emitter delete params
type EmitterDeleteHandler interface {
	Handle(EmitterDeleteParams, interface{}) middleware.Responder
}

// NewEmitterDelete creates a new http.Handler for the emitter delete operation
func NewEmitterDelete(ctx *middleware.Context, handler EmitterDeleteHandler) *EmitterDelete {
	return &EmitterDelete{Context: ctx, Handler: handler}
}

/*EmitterDelete swagger:route DELETE /emitters/{emitter_id} emitter emitterDelete

Get a list of telemetry emitters

Returns the request collected object

*/
type EmitterDelete struct {
	Context *middleware.Context
	Handler EmitterDeleteHandler
}

func (o *EmitterDelete) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewEmitterDeleteParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
