name: autopilot
version: 1.0.0
license:
  owner: Portworx
  type: APACHE
  header: |
    Copyright 2018 Portworx Inc. All rights reserved.
    Use of this source code is governed by the Apache 2.0
    license that can be found in the LICENSE file.