---
swagger: "2.0"
info:
  description: "libopenstorage autopilot API"
  version: "1.0.0"
  title: "autopilot"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost:9000"
schemes:
- "http"
security:
- basicAuth: []
paths:
  /collectors:
    get:
      tags:
      - "collector"
      summary: "Get a list of telemetry collectors"
      description: "Returns an array of telemetry collectors defined in the system"
      operationId: "collectorList"
      parameters: []
      responses:
        200:
          description: "OK"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Collector"
        500:
          description: "ServerError"
          examples:
            application/json:
              message: "internal server error"
          schema:
            $ref: "#/definitions/Error"
    post:
      tags:
      - "collector"
      summary: "Create a new telemetry collector"
      description: "Create a new telemetry collector from the provided definition"
      operationId: "collectorCreate"
      parameters:
      - in: "body"
        name: "collector"
        description: "The collector to create"
        required: true
        schema:
          $ref: "#/definitions/Collector"
      responses:
        201:
          description: "Created"
          schema:
            $ref: "#/definitions/Collector"
        400:
          description: "BadRequest"
          examples:
            application/json:
              message: "invalid parameter"
          schema:
            $ref: "#/definitions/Error"
        500:
          description: "ServerError"
          examples:
            application/json:
              message: "internal server error"
          schema:
            $ref: "#/definitions/Error"
  /collectors/{collector_id}:
    get:
      tags:
      - "collector"
      summary: "Get a list of telemetry collectors"
      description: "Returns the request collected object"
      operationId: "collectorGet"
      parameters:
      - name: "collector_id"
        in: "path"
        description: "The id of the collector"
        required: true
        type: "string"
        format: "uuid"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/Collector"
        400:
          description: "BadRequest"
          examples:
            application/json:
              message: "invalid parameter"
          schema:
            $ref: "#/definitions/Error"
        404:
          description: "NotFound"
          examples:
            application/json:
              message: "object not found"
          schema:
            $ref: "#/definitions/Error"
        500:
          description: "ServerError"
          examples:
            application/json:
              message: "internal server error"
          schema:
            $ref: "#/definitions/Error"
    put:
      tags:
      - "collector"
      summary: "Update a collector object"
      description: "Update the properties of the specified collector"
      operationId: "collectorUpdate"
      parameters:
      - name: "collector_id"
        in: "path"
        description: "The id of the collector"
        required: true
        type: "string"
        format: "uuid"
      - in: "body"
        name: "collector"
        description: "The collector to create"
        required: true
        schema:
          $ref: "#/definitions/Collector"
      responses:
        204:
          description: "No Content"
        400:
          description: "BadRequest"
          examples:
            application/json:
              message: "invalid parameter"
          schema:
            $ref: "#/definitions/Error"
        500:
          description: "ServerError"
          examples:
            application/json:
              message: "internal server error"
          schema:
            $ref: "#/definitions/Error"
    delete:
      tags:
      - "collector"
      summary: "Get a list of telemetry collectors"
      description: "Returns the request collected object"
      operationId: "collectorDelete"
      parameters:
      - name: "collector_id"
        in: "path"
        description: "The id of the collector"
        required: true
        type: "string"
        format: "uuid"
      responses:
        204:
          description: "No Content"
        404:
          description: "NotFound"
          examples:
            application/json:
              message: "object not found"
          schema:
            $ref: "#/definitions/Error"
        500:
          description: "ServerError"
          examples:
            application/json:
              message: "internal server error"
          schema:
            $ref: "#/definitions/Error"
securityDefinitions:
  basicAuth:
    type: "basic"
definitions:
  Collector:
    properties:
      id:
        type: "string"
        format: "uuid"
        description: "The collector id"
      provider:
        type: "string"
        description: "The telemetry provider for the collector"
        enum:
        - "prometheus"
      params:
        type: "object"
        description: "The parameters to pass to the provider"
        additionalProperties:
          type: "object"
          properties: {}
    description: "A collector pulls data from a telemetry provider, parses, \nand\
      \ reformats the data to be consumed by the autopilot engine.\n"
    example:
      provider: "prometheus"
      id: "046b6c7f-0b8a-43b9-b35d-6489e6daee91"
      params:
        key: "{}"
  Task:
    properties:
      id:
        type: "string"
        format: "uuid"
        description: "The task id"
      type:
        type: "string"
        description: "The task type"
        enum:
        - "collector"
      params:
        type: "object"
        description: "The parameters to pass to the provider"
        additionalProperties:
          type: "object"
          properties: {}
      run_at:
        type: "string"
        format: "date-time"
        description: "The timestamp the next execution of the task"
      interval:
        type: "string"
        description: "The task run interval"
      status:
        type: "string"
        description: "The task status"
        enum:
        - "pending"
        - "running"
        - "succeeded"
        - "failed"
    description: "A task is a scheduled operation in the engine\n"
  Sample:
    properties:
      id:
        type: "string"
        format: "uuid"
        description: "The sample id"
      provider:
        type: "string"
        description: "The telemetry provider for the collector"
        enum:
        - "prometheus"
      created_at:
        type: "string"
        format: "date-time"
        description: "The timestamp for the sample"
      meta:
        type: "object"
        description: "Provider specific meta data"
        additionalProperties:
          type: "object"
          properties: {}
    description: "A sample is a set of collected data from a particular provider that\
      \ has be reformatted\nand prepared for consumption. The sample data itself is\
      \ stored in the filesystem.\n"
  Error:
    type: "object"
    properties:
      code:
        type: "string"
        description: "The error code"
        x-nullable: true
      message:
        type: "string"
        description: "The error message"
      detail:
        type: "object"
        description: "The error details"
        additionalProperties:
          type: "string"
        x-omitempty: true
        x-nullable: true
    description: "Common Error Model"
responses:
  NotFound:
    description: "NotFound"
    examples:
      application/json:
        message: "object not found"
    schema:
      $ref: "#/definitions/Error"
  Unauthorized:
    description: "Unauthorized"
    examples:
      application/json:
        message: "access denied"
    schema:
      $ref: "#/definitions/Error"
  BadRequest:
    description: "BadRequest"
    examples:
      application/json:
        message: "invalid parameter"
    schema:
      $ref: "#/definitions/Error"
  ServerError:
    description: "ServerError"
    examples:
      application/json:
        message: "internal server error"
    schema:
      $ref: "#/definitions/Error"
