---
swagger: "2.0"
info:
  description: "libopenstorage autopilot API"
  version: "1.0.0"
  title: "autopilot"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
paths:
  /sources:
    get:
      summary: "Get a list of telemetry sources"
      description: "Returns an array of telemetry sources defined in the system"
      operationId: "telemetrySourceList"
      parameters: []
      responses:
        200:
          description: "OK"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Source"
definitions:
  Source:
    properties:
      id:
        type: "string"
        format: "uuid"
    description: "A definition for a telemetry source"
    example:
      id: "046b6c7f-0b8a-43b9-b35d-6489e6daee91"
